version: 2

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/codecrafters
    binary: codecrafters
    ldflags: "-s -w -X github.com/codecrafters-io/coderbot-cli/internal/utils.Version={{.Version}} -X github.com/codecrafters-io/coderbot-cli/internal/utils.Commit={{.Commit}}"

archives:
  - name_template: "{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
