name: Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  smoke_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - run: make build
      - run: dist/codecrafters --version
